stages:
  - build
  - docker_build
  - deploy
build_dist:
  image: 'node:latest'
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - 'npm --registry=https://registry.npm.taobao.org install'
#    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  tags:
    - docker
build_docker_image:
  image: docker
  stage: docker_build
  script:
    - 'docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.yunbaoguan.cn:5005'
    - 'docker build -t git.yunbaoguan.cn:5005/websites/201807/www/image:$CI_PIPELINE_ID .'
    - 'docker push git.yunbaoguan.cn:5005/websites/201807/www/image:$CI_PIPELINE_ID'
  tags:
    - image
  only:
    - master
deploy_dev:
  image: docker
  stage: deploy
  environment:
    name: dev
    url: 'http://192.168.3.146:83'
  script:
    - 'docker -H 192.168.3.146 login -u gitlab-ci-token -p $CI_JOB_TOKEN git.yunbaoguan.cn:5005'
    - 'docker -H 192.168.3.146 pull git.yunbaoguan.cn:5005/websites/201807/www/image:$CI_PIPELINE_ID || true'
    - 'docker -H 192.168.3.146 stop www || true'
    - 'docker -H 192.168.3.146 rm www || true'
    - 'docker -H 192.168.3.146 run -d --restart=always -p 84:80 --name www git.yunbaoguan.cn:5005/websites/201807/www/image:$CI_PIPELINE_ID'
  tags:
    - image
  only:
    - master
deploy_prod:
  stage: deploy
  environment:
    name: prod
    url: 'https://www.yunbaoguan.cn'
  before_script:
    - 'eval $(ssh-agent -s)'
    - 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - 'mkdir -p ~/.ssh'
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - 'docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.yunbaoguan.cn:5005'
    - 'docker pull git.yunbaoguan.cn:5005/websites/201807/www/image:$CI_PIPELINE_ID'
    - 'docker save git.yunbaoguan.cn:5005/websites/201807/www/image:$CI_PIPELINE_ID | bzip2 | pv | ssh deployer@ppbe.yunbaoguan.cn "bunzip2 | docker load"'
    - 'ssh deployer@ppbe.yunbaoguan.cn "( docker stop www; docker rm www) || true"'
    - 'ssh deployer@ppbe.yunbaoguan.cn "docker run -d --restart=always --name=www -e VIRTUAL_HOST=www.yunbaoguan.cn git.yunbaoguan.cn:5005/websites/201807/www/image:$CI_PIPELINE_ID"'
  tags:
    - shell
  when: manual
  only:
    - master
